### ISSUE TITLE
why these permissions exist?

### ISSUE THREAD

**Issue by KiraiEEE** [theapache64/SoundCloud-Downloader#6]
![IMG_20221120_183135.jpg](https://user-images.githubusercontent.com/54278089/202916900-d7ba22f3-f7c9-4e0f-bb85-1d7e010db76a.jpg)

**Comment by mb2g17** [comment]
Agreed; surely, if the app's purpose is to scrub SoundCloud and download music files, the only permission this app would need is Storage 🤔
